version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=rabbithole
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
